server:
    port: 8085
    servlet:
        context-path: /goldenhour

## default connection pool
spring:
    profiles:
        active: ${ACTIVE_PROFILE:dev}
    jpa:
        hibernate:
            ddl-auto: none # When you launch the application for the first time outside Docker - switch "none" to "create"
            show-sql: true
            database: postgresql
            database-platform: org.hibernate.dialect.PostgreSQLDialect
            open-in-view: false
            generate-ddl: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect